version: "2"

services:
  mongodb:
    image: mongo:latest
    container_name: "frush_mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - ./mongo:/data/db
      - ./logs:/data/logs
    ports:
      - 27017:27017
    command: --smallfiles
  gunicorn:
    container_name: "frush_flask"
    build:
      context: ./docker
      dockerfile: gunicorn
    working_dir: /app
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - "5000:8000"
    volumes:
      - .:/app
    command: gunicorn app:app -w 4 -b 0.0.0.0:8000 --log-level DEBUG --log-file test.log --reload
